# This file is needed for testing purposes. Storing debug and test data here.

# Example of parsed response from weather api:
mocked_json = {'message': 0.0029, 'list': [{'sys': {'pod': 'n'}, 'rain': {'3h': 0.05}, 'weather': [
    {'id': 500, 'icon': '10n', 'main': 'Rain', 'description': 'light rain'}], 'clouds': {'all': 80},
                                            'dt_txt': '2016-05-15 18:00:00', 'dt': 1463335200,
                                            'main': {'pressure': 1006.36, 'grnd_level': 1006.36, 'temp': 287.52,
                                                     'temp_min': 286.801, 'temp_max': 287.52, 'sea_level': 1020.61,
                                                     'humidity': 93, 'temp_kf': 0.72},
                                            'wind': {'deg': 310.004, 'speed': 6.88}},
                                           {'sys': {'pod': 'n'}, 'rain': {'3h': 0.165}, 'weather': [
                                               {'id': 500, 'icon': '10n', 'main': 'Rain', 'description': 'light rain'}],
                                            'clouds': {'all': 48}, 'dt_txt': '2016-05-15 21:00:00', 'dt': 1463346000,
                                            'main': {'pressure': 1008.18, 'grnd_level': 1008.18, 'temp': 286.36,
                                                     'temp_min': 285.679, 'temp_max': 286.36, 'sea_level': 1022.61,
                                                     'humidity': 90, 'temp_kf': 0.68},
                                            'wind': {'deg': 316.001, 'speed': 5.67}}, {'sys': {'pod': 'n'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 800, 'icon': '01n',
                                                                                            'main': 'Clear',
                                                                                            'description': 'clear sky'}],
                                                                                       'clouds': {'all': 0},
                                                                                       'dt_txt': '2016-05-16 00:00:00',
                                                                                       'dt': 1463356800,
                                                                                       'main': {'pressure': 1009.58,
                                                                                                'grnd_level': 1009.58,
                                                                                                'temp': 284.07,
                                                                                                'temp_min': 283.434,
                                                                                                'temp_max': 284.07,
                                                                                                'sea_level': 1024.14,
                                                                                                'humidity': 90,
                                                                                                'temp_kf': 0.64},
                                                                                       'wind': {'deg': 313.502,
                                                                                                'speed': 6.41}},
                                           {'sys': {'pod': 'd'}, 'rain': {}, 'weather': [
                                               {'id': 800, 'icon': '01d', 'main': 'Clear', 'description': 'clear sky'}],
                                            'clouds': {'all': 0}, 'dt_txt': '2016-05-16 03:00:00', 'dt': 1463367600,
                                            'main': {'pressure': 1010.78, 'grnd_level': 1010.78, 'temp': 282.29,
                                                     'temp_min': 281.694, 'temp_max': 282.29, 'sea_level': 1025.29,
                                                     'humidity': 90, 'temp_kf': 0.6},
                                            'wind': {'deg': 319.504, 'speed': 5.16}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 800, 'icon': '01d',
                                                                                            'main': 'Clear',
                                                                                            'description': 'clear sky'}],
                                                                                       'clouds': {'all': 0},
                                                                                       'dt_txt': '2016-05-16 06:00:00',
                                                                                       'dt': 1463378400,
                                                                                       'main': {'pressure': 1011.7,
                                                                                                'grnd_level': 1011.7,
                                                                                                'temp': 285.53,
                                                                                                'temp_min': 284.973,
                                                                                                'temp_max': 285.53,
                                                                                                'sea_level': 1026.1,
                                                                                                'humidity': 89,
                                                                                                'temp_kf': 0.56},
                                                                                       'wind': {'deg': 328,
                                                                                                'speed': 4.74}},
                                           {'sys': {'pod': 'd'}, 'rain': {}, 'weather': [
                                               {'id': 802, 'icon': '03d', 'main': 'Clouds',
                                                'description': 'scattered clouds'}], 'clouds': {'all': 32},
                                            'dt_txt': '2016-05-16 09:00:00', 'dt': 1463389200,
                                            'main': {'pressure': 1012.35, 'grnd_level': 1012.35, 'temp': 288.33,
                                                     'temp_min': 287.815, 'temp_max': 288.33, 'sea_level': 1026.75,
                                                     'humidity': 82, 'temp_kf': 0.52},
                                            'wind': {'deg': 318.004, 'speed': 3.52}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 801, 'icon': '02d',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'few clouds'}],
                                                                                       'clouds': {'all': 12},
                                                                                       'dt_txt': '2016-05-16 12:00:00',
                                                                                       'dt': 1463400000,
                                                                                       'main': {'pressure': 1012.15,
                                                                                                'grnd_level': 1012.15,
                                                                                                'temp': 289.93,
                                                                                                'temp_min': 289.45,
                                                                                                'temp_max': 289.93,
                                                                                                'sea_level': 1026.49,
                                                                                                'humidity': 76,
                                                                                                'temp_kf': 0.48},
                                                                                       'wind': {'deg': 312.5,
                                                                                                'speed': 3.31}},
                                           {'sys': {'pod': 'd'}, 'rain': {}, 'weather': [
                                               {'id': 802, 'icon': '03d', 'main': 'Clouds',
                                                'description': 'scattered clouds'}], 'clouds': {'all': 36},
                                            'dt_txt': '2016-05-16 15:00:00', 'dt': 1463410800,
                                            'main': {'pressure': 1011.68, 'grnd_level': 1011.68, 'temp': 289.61,
                                                     'temp_min': 289.172, 'temp_max': 289.61, 'sea_level': 1025.9,
                                                     'humidity': 67, 'temp_kf': 0.44},
                                            'wind': {'deg': 317.501, 'speed': 2.93}}, {'sys': {'pod': 'n'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 803, 'icon': '04n',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'broken clouds'}],
                                                                                       'clouds': {'all': 80},
                                                                                       'dt_txt': '2016-05-16 18:00:00',
                                                                                       'dt': 1463421600,
                                                                                       'main': {'pressure': 1011.63,
                                                                                                'grnd_level': 1011.63,
                                                                                                'temp': 287.15,
                                                                                                'temp_min': 286.749,
                                                                                                'temp_max': 287.15,
                                                                                                'sea_level': 1025.99,
                                                                                                'humidity': 64,
                                                                                                'temp_kf': 0.4},
                                                                                       'wind': {'deg': 313.501,
                                                                                                'speed': 2.79}},
                                           {'sys': {'pod': 'n'}, 'rain': {'3h': 0.01}, 'weather': [
                                               {'id': 500, 'icon': '10n', 'main': 'Rain', 'description': 'light rain'}],
                                            'clouds': {'all': 88}, 'dt_txt': '2016-05-16 21:00:00', 'dt': 1463432400,
                                            'main': {'pressure': 1012.05, 'grnd_level': 1012.05, 'temp': 284.73,
                                                     'temp_min': 284.375, 'temp_max': 284.73, 'sea_level': 1026.45,
                                                     'humidity': 76, 'temp_kf': 0.36},
                                            'wind': {'deg': 331.5, 'speed': 4.56}},
                                           {'sys': {'pod': 'n'}, 'rain': {'3h': 0.33}, 'weather': [
                                               {'id': 500, 'icon': '10n', 'main': 'Rain', 'description': 'light rain'}],
                                            'clouds': {'all': 88}, 'dt_txt': '2016-05-17 00:00:00', 'dt': 1463443200,
                                            'main': {'pressure': 1010.99, 'grnd_level': 1010.99, 'temp': 283.43,
                                                     'temp_min': 283.108, 'temp_max': 283.43, 'sea_level': 1025.47,
                                                     'humidity': 89, 'temp_kf': 0.32},
                                            'wind': {'deg': 356.003, 'speed': 5.33}},
                                           {'sys': {'pod': 'd'}, 'rain': {'3h': 1.28}, 'weather': [
                                               {'id': 500, 'icon': '10d', 'main': 'Rain', 'description': 'light rain'}],
                                            'clouds': {'all': 92}, 'dt_txt': '2016-05-17 03:00:00', 'dt': 1463454000,
                                            'main': {'pressure': 1010.23, 'grnd_level': 1010.23, 'temp': 282.3,
                                                     'temp_min': 282.025, 'temp_max': 282.3, 'sea_level': 1024.7,
                                                     'humidity': 99, 'temp_kf': 0.28},
                                            'wind': {'deg': 350.503, 'speed': 6.01}},
                                           {'sys': {'pod': 'd'}, 'rain': {'3h': 5.81}, 'weather': [
                                               {'id': 501, 'icon': '10d', 'main': 'Rain',
                                                'description': 'moderate rain'}], 'clouds': {'all': 92},
                                            'dt_txt': '2016-05-17 06:00:00', 'dt': 1463464800,
                                            'main': {'pressure': 1009.45, 'grnd_level': 1009.45, 'temp': 282.59,
                                                     'temp_min': 282.355, 'temp_max': 282.59, 'sea_level': 1023.76,
                                                     'humidity': 100, 'temp_kf': 0.24},
                                            'wind': {'deg': 2.00055, 'speed': 6.55}},
                                           {'sys': {'pod': 'd'}, 'rain': {'3h': 2.34}, 'weather': [
                                               {'id': 500, 'icon': '10d', 'main': 'Rain', 'description': 'light rain'}],
                                            'clouds': {'all': 92}, 'dt_txt': '2016-05-17 09:00:00', 'dt': 1463475600,
                                            'main': {'pressure': 1008.63, 'grnd_level': 1008.63, 'temp': 283.22,
                                                     'temp_min': 283.017, 'temp_max': 283.22, 'sea_level': 1022.95,
                                                     'humidity': 100, 'temp_kf': 0.2},
                                            'wind': {'deg': 352.002, 'speed': 6.81}},
                                           {'sys': {'pod': 'd'}, 'rain': {'3h': 1.19}, 'weather': [
                                               {'id': 500, 'icon': '10d', 'main': 'Rain', 'description': 'light rain'}],
                                            'clouds': {'all': 92}, 'dt_txt': '2016-05-17 12:00:00', 'dt': 1463486400,
                                            'main': {'pressure': 1008.54, 'grnd_level': 1008.54, 'temp': 283.42,
                                                     'temp_min': 283.257, 'temp_max': 283.42, 'sea_level': 1022.8,
                                                     'humidity': 100, 'temp_kf': 0.16},
                                            'wind': {'deg': 336.002, 'speed': 6.76}},
                                           {'sys': {'pod': 'd'}, 'rain': {'3h': 1.4}, 'weather': [
                                               {'id': 500, 'icon': '10d', 'main': 'Rain', 'description': 'light rain'}],
                                            'clouds': {'all': 92}, 'dt_txt': '2016-05-17 15:00:00', 'dt': 1463497200,
                                            'main': {'pressure': 1008.2, 'grnd_level': 1008.2, 'temp': 282.98,
                                                     'temp_min': 282.861, 'temp_max': 282.98, 'sea_level': 1022.59,
                                                     'humidity': 100, 'temp_kf': 0.12},
                                            'wind': {'deg': 329.005, 'speed': 6.56}},
                                           {'sys': {'pod': 'n'}, 'rain': {'3h': 0.06}, 'weather': [
                                               {'id': 500, 'icon': '10n', 'main': 'Rain', 'description': 'light rain'}],
                                            'clouds': {'all': 80}, 'dt_txt': '2016-05-17 18:00:00', 'dt': 1463508000,
                                            'main': {'pressure': 1008.86, 'grnd_level': 1008.86, 'temp': 282.56,
                                                     'temp_min': 282.484, 'temp_max': 282.56, 'sea_level': 1023.25,
                                                     'humidity': 93, 'temp_kf': 0.08},
                                            'wind': {'deg': 318.502, 'speed': 5.12}}, {'sys': {'pod': 'n'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 803, 'icon': '04n',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'broken clouds'}],
                                                                                       'clouds': {'all': 64},
                                                                                       'dt_txt': '2016-05-17 21:00:00',
                                                                                       'dt': 1463518800,
                                                                                       'main': {'pressure': 1009.2,
                                                                                                'grnd_level': 1009.2,
                                                                                                'temp': 281.96,
                                                                                                'temp_min': 281.917,
                                                                                                'temp_max': 281.96,
                                                                                                'sea_level': 1023.8,
                                                                                                'humidity': 97,
                                                                                                'temp_kf': 0.04},
                                                                                       'wind': {'deg': 287.002,
                                                                                                'speed': 4.01}},
                                           {'sys': {'pod': 'n'}, 'rain': {}, 'weather': [
                                               {'id': 800, 'icon': '01n', 'main': 'Clear', 'description': 'clear sky'}],
                                            'clouds': {'all': 0}, 'dt_txt': '2016-05-18 00:00:00', 'dt': 1463529600,
                                            'main': {'pressure': 1009.7, 'grnd_level': 1009.7, 'temp': 279.94,
                                                     'temp_min': 279.94, 'temp_max': 279.94, 'sea_level': 1024.38,
                                                     'humidity': 96, 'temp_kf': 0},
                                            'wind': {'deg': 287.001, 'speed': 5.26}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 800, 'icon': '01d',
                                                                                            'main': 'Clear',
                                                                                            'description': 'clear sky'}],
                                                                                       'clouds': {'all': 0},
                                                                                       'dt_txt': '2016-05-18 03:00:00',
                                                                                       'dt': 1463540400,
                                                                                       'main': {'pressure': 1010.75,
                                                                                                'grnd_level': 1010.75,
                                                                                                'temp': 278.818,
                                                                                                'temp_min': 278.818,
                                                                                                'temp_max': 278.818,
                                                                                                'sea_level': 1025.45,
                                                                                                'humidity': 95,
                                                                                                'temp_kf': 0},
                                                                                       'wind': {'deg': 292.501,
                                                                                                'speed': 4.87}},
                                           {'sys': {'pod': 'd'}, 'rain': {}, 'weather': [
                                               {'id': 800, 'icon': '01d', 'main': 'Clear', 'description': 'clear sky'}],
                                            'clouds': {'all': 0}, 'dt_txt': '2016-05-18 06:00:00', 'dt': 1463551200,
                                            'main': {'pressure': 1011.7, 'grnd_level': 1011.7, 'temp': 283.686,
                                                     'temp_min': 283.686, 'temp_max': 283.686, 'sea_level': 1026.14,
                                                     'humidity': 97, 'temp_kf': 0},
                                            'wind': {'deg': 292, 'speed': 4.07}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                   'weather': [
                                                                                       {'id': 800, 'icon': '01d',
                                                                                        'main': 'Clear',
                                                                                        'description': 'clear sky'}],
                                                                                   'clouds': {'all': 0},
                                                                                   'dt_txt': '2016-05-18 09:00:00',
                                                                                   'dt': 1463562000,
                                                                                   'main': {'pressure': 1012.34,
                                                                                            'grnd_level': 1012.34,
                                                                                            'temp': 286.954,
                                                                                            'temp_min': 286.954,
                                                                                            'temp_max': 286.954,
                                                                                            'sea_level': 1026.64,
                                                                                            'humidity': 95,
                                                                                            'temp_kf': 0},
                                                                                   'wind': {'deg': 280.502,
                                                                                            'speed': 4.13}},
                                           {'sys': {'pod': 'd'}, 'rain': {}, 'weather': [
                                               {'id': 802, 'icon': '03d', 'main': 'Clouds',
                                                'description': 'scattered clouds'}], 'clouds': {'all': 36},
                                            'dt_txt': '2016-05-18 12:00:00', 'dt': 1463572800,
                                            'main': {'pressure': 1012.26, 'grnd_level': 1012.26, 'temp': 287.575,
                                                     'temp_min': 287.575, 'temp_max': 287.575, 'sea_level': 1026.62,
                                                     'humidity': 80, 'temp_kf': 0},
                                            'wind': {'deg': 282.502, 'speed': 3.93}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 802, 'icon': '03d',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'scattered clouds'}],
                                                                                       'clouds': {'all': 48},
                                                                                       'dt_txt': '2016-05-18 15:00:00',
                                                                                       'dt': 1463583600,
                                                                                       'main': {'pressure': 1012.48,
                                                                                                'grnd_level': 1012.48,
                                                                                                'temp': 287.376,
                                                                                                'temp_min': 287.376,
                                                                                                'temp_max': 287.376,
                                                                                                'sea_level': 1026.83,
                                                                                                'humidity': 68,
                                                                                                'temp_kf': 0},
                                                                                       'wind': {'deg': 287.001,
                                                                                                'speed': 3.41}},
                                           {'sys': {'pod': 'n'}, 'rain': {}, 'weather': [
                                               {'id': 803, 'icon': '04n', 'main': 'Clouds',
                                                'description': 'broken clouds'}], 'clouds': {'all': 80},
                                            'dt_txt': '2016-05-18 18:00:00', 'dt': 1463594400,
                                            'main': {'pressure': 1013, 'grnd_level': 1013, 'temp': 285.089,
                                                     'temp_min': 285.089, 'temp_max': 285.089, 'sea_level': 1027.56,
                                                     'humidity': 68, 'temp_kf': 0},
                                            'wind': {'deg': 268.002, 'speed': 2.11}}, {'sys': {'pod': 'n'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 802, 'icon': '03n',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'scattered clouds'}],
                                                                                       'clouds': {'all': 44},
                                                                                       'dt_txt': '2016-05-18 21:00:00',
                                                                                       'dt': 1463605200,
                                                                                       'main': {'pressure': 1013.48,
                                                                                                'grnd_level': 1013.48,
                                                                                                'temp': 282.775,
                                                                                                'temp_min': 282.775,
                                                                                                'temp_max': 282.775,
                                                                                                'sea_level': 1028.11,
                                                                                                'humidity': 73,
                                                                                                'temp_kf': 0},
                                                                                       'wind': {'deg': 258.006,
                                                                                                'speed': 2.32}},
                                           {'sys': {'pod': 'n'}, 'rain': {}, 'weather': [
                                               {'id': 800, 'icon': '02n', 'main': 'Clear', 'description': 'clear sky'}],
                                            'clouds': {'all': 8}, 'dt_txt': '2016-05-19 00:00:00', 'dt': 1463616000,
                                            'main': {'pressure': 1013.47, 'grnd_level': 1013.47, 'temp': 280.034,
                                                     'temp_min': 280.034, 'temp_max': 280.034, 'sea_level': 1028.17,
                                                     'humidity': 88, 'temp_kf': 0},
                                            'wind': {'deg': 231.005, 'speed': 1.32}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 802, 'icon': '03d',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'scattered clouds'}],
                                                                                       'clouds': {'all': 48},
                                                                                       'dt_txt': '2016-05-19 03:00:00',
                                                                                       'dt': 1463626800,
                                                                                       'main': {'pressure': 1013.65,
                                                                                                'grnd_level': 1013.65,
                                                                                                'temp': 279.147,
                                                                                                'temp_min': 279.147,
                                                                                                'temp_max': 279.147,
                                                                                                'sea_level': 1028.43,
                                                                                                'humidity': 88,
                                                                                                'temp_kf': 0},
                                                                                       'wind': {'deg': 207.001,
                                                                                                'speed': 1.32}},
                                           {'sys': {'pod': 'd'}, 'rain': {}, 'weather': [
                                               {'id': 803, 'icon': '04d', 'main': 'Clouds',
                                                'description': 'broken clouds'}], 'clouds': {'all': 68},
                                            'dt_txt': '2016-05-19 06:00:00', 'dt': 1463637600,
                                            'main': {'pressure': 1014.29, 'grnd_level': 1014.29, 'temp': 285.766,
                                                     'temp_min': 285.766, 'temp_max': 285.766, 'sea_level': 1028.66,
                                                     'humidity': 81, 'temp_kf': 0},
                                            'wind': {'deg': 215.501, 'speed': 2.01}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 800, 'icon': '01d',
                                                                                            'main': 'Clear',
                                                                                            'description': 'clear sky'}],
                                                                                       'clouds': {'all': 0},
                                                                                       'dt_txt': '2016-05-19 09:00:00',
                                                                                       'dt': 1463648400,
                                                                                       'main': {'pressure': 1014.23,
                                                                                                'grnd_level': 1014.23,
                                                                                                'temp': 288.579,
                                                                                                'temp_min': 288.579,
                                                                                                'temp_max': 288.579,
                                                                                                'sea_level': 1028.44,
                                                                                                'humidity': 84,
                                                                                                'temp_kf': 0},
                                                                                       'wind': {'deg': 207.503,
                                                                                                'speed': 2.56}},
                                           {'sys': {'pod': 'd'}, 'rain': {}, 'weather': [
                                               {'id': 801, 'icon': '02d', 'main': 'Clouds',
                                                'description': 'few clouds'}], 'clouds': {'all': 24},
                                            'dt_txt': '2016-05-19 12:00:00', 'dt': 1463659200,
                                            'main': {'pressure': 1013.55, 'grnd_level': 1013.55, 'temp': 289.824,
                                                     'temp_min': 289.824, 'temp_max': 289.824, 'sea_level': 1027.88,
                                                     'humidity': 75, 'temp_kf': 0},
                                            'wind': {'deg': 205.5, 'speed': 2.96}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                     'weather': [
                                                                                         {'id': 803, 'icon': '04d',
                                                                                          'main': 'Clouds',
                                                                                          'description': 'broken clouds'}],
                                                                                     'clouds': {'all': 64},
                                                                                     'dt_txt': '2016-05-19 15:00:00',
                                                                                     'dt': 1463670000,
                                                                                     'main': {'pressure': 1013.21,
                                                                                              'grnd_level': 1013.21,
                                                                                              'temp': 289.238,
                                                                                              'temp_min': 289.238,
                                                                                              'temp_max': 289.238,
                                                                                              'sea_level': 1027.58,
                                                                                              'humidity': 63,
                                                                                              'temp_kf': 0},
                                                                                     'wind': {'deg': 223.501,
                                                                                              'speed': 3.01}},
                                           {'sys': {'pod': 'n'}, 'rain': {}, 'weather': [
                                               {'id': 802, 'icon': '03n', 'main': 'Clouds',
                                                'description': 'scattered clouds'}], 'clouds': {'all': 32},
                                            'dt_txt': '2016-05-19 18:00:00', 'dt': 1463680800,
                                            'main': {'pressure': 1013.58, 'grnd_level': 1013.58, 'temp': 286.069,
                                                     'temp_min': 286.069, 'temp_max': 286.069, 'sea_level': 1027.99,
                                                     'humidity': 66, 'temp_kf': 0},
                                            'wind': {'deg': 198.501, 'speed': 1.87}}, {'sys': {'pod': 'n'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 801, 'icon': '02n',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'few clouds'}],
                                                                                       'clouds': {'all': 20},
                                                                                       'dt_txt': '2016-05-19 21:00:00',
                                                                                       'dt': 1463691600,
                                                                                       'main': {'pressure': 1013.81,
                                                                                                'grnd_level': 1013.81,
                                                                                                'temp': 282.744,
                                                                                                'temp_min': 282.744,
                                                                                                'temp_max': 282.744,
                                                                                                'sea_level': 1028.37,
                                                                                                'humidity': 80,
                                                                                                'temp_kf': 0},
                                                                                       'wind': {'deg': 199.504,
                                                                                                'speed': 2.21}},
                                           {'sys': {'pod': 'n'}, 'rain': {}, 'weather': [
                                               {'id': 800, 'icon': '01n', 'main': 'Clear', 'description': 'clear sky'}],
                                            'clouds': {'all': 0}, 'dt_txt': '2016-05-20 00:00:00', 'dt': 1463702400,
                                            'main': {'pressure': 1013.45, 'grnd_level': 1013.45, 'temp': 280.502,
                                                     'temp_min': 280.502, 'temp_max': 280.502, 'sea_level': 1028.04,
                                                     'humidity': 87, 'temp_kf': 0},
                                            'wind': {'deg': 177.506, 'speed': 1.21}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 802, 'icon': '03d',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'scattered clouds'}],
                                                                                       'clouds': {'all': 36},
                                                                                       'dt_txt': '2016-05-20 03:00:00',
                                                                                       'dt': 1463713200,
                                                                                       'main': {'pressure': 1013.26,
                                                                                                'grnd_level': 1013.26,
                                                                                                'temp': 280.821,
                                                                                                'temp_min': 280.821,
                                                                                                'temp_max': 280.821,
                                                                                                'sea_level': 1027.83,
                                                                                                'humidity': 86,
                                                                                                'temp_kf': 0},
                                                                                       'wind': {'deg': 187.001,
                                                                                                'speed': 1.37}},
                                           {'sys': {'pod': 'd'}, 'rain': {}, 'weather': [
                                               {'id': 800, 'icon': '01d', 'main': 'Clear', 'description': 'clear sky'}],
                                            'clouds': {'all': 0}, 'dt_txt': '2016-05-20 06:00:00', 'dt': 1463724000,
                                            'main': {'pressure': 1013.42, 'grnd_level': 1013.42, 'temp': 287.679,
                                                     'temp_min': 287.679, 'temp_max': 287.679, 'sea_level': 1027.73,
                                                     'humidity': 85, 'temp_kf': 0},
                                            'wind': {'deg': 234.002, 'speed': 2.56}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 801, 'icon': '02d',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'few clouds'}],
                                                                                       'clouds': {'all': 12},
                                                                                       'dt_txt': '2016-05-20 09:00:00',
                                                                                       'dt': 1463734800,
                                                                                       'main': {'pressure': 1012.8,
                                                                                                'grnd_level': 1012.8,
                                                                                                'temp': 290.35,
                                                                                                'temp_min': 290.35,
                                                                                                'temp_max': 290.35,
                                                                                                'sea_level': 1027.09,
                                                                                                'humidity': 87,
                                                                                                'temp_kf': 0},
                                                                                       'wind': {'deg': 230,
                                                                                                'speed': 2.56}},
                                           {'sys': {'pod': 'd'}, 'rain': {}, 'weather': [
                                               {'id': 802, 'icon': '03d', 'main': 'Clouds',
                                                'description': 'scattered clouds'}], 'clouds': {'all': 36},
                                            'dt_txt': '2016-05-20 12:00:00', 'dt': 1463745600,
                                            'main': {'pressure': 1011.49, 'grnd_level': 1011.49, 'temp': 292.317,
                                                     'temp_min': 292.317, 'temp_max': 292.317, 'sea_level': 1025.65,
                                                     'humidity': 76, 'temp_kf': 0},
                                            'wind': {'deg': 275.003, 'speed': 3.13}}, {'sys': {'pod': 'd'}, 'rain': {},
                                                                                       'weather': [
                                                                                           {'id': 802, 'icon': '03d',
                                                                                            'main': 'Clouds',
                                                                                            'description': 'scattered clouds'}],
                                                                                       'clouds': {'all': 32},
                                                                                       'dt_txt': '2016-05-20 15:00:00',
                                                                                       'dt': 1463756400,
                                                                                       'main': {'pressure': 1010.76,
                                                                                                'grnd_level': 1010.76,
                                                                                                'temp': 292.408,
                                                                                                'temp_min': 292.408,
                                                                                                'temp_max': 292.408,
                                                                                                'sea_level': 1025.02,
                                                                                                'humidity': 67,
                                                                                                'temp_kf': 0},
                                                                                       'wind': {'deg': 286.501,
                                                                                                'speed': 4.21}}],
               'cnt': 40, 'cod': '200',
               'city': {'name': 'Kiev', 'coord': {'lat': 50.433334, 'lon': 30.516666}, 'population': 0,
                        'sys': {'population': 0}, 'id': 703448, 'country': 'UA'}}


if __name__ == "__main__":
    for item in mocked_json['list']:
        import time
        parsed_time = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(item['dt']))

        print(parsed_time)